// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn5_lJE1uLADyc7aI01DbLftkIyvlJkfQ',
    appId: '1:990092518872:web:1c1402099804774f3f7ead',
    messagingSenderId: '990092518872',
    projectId: 'step-counter-d044d',
    authDomain: 'step-counter-d044d.firebaseapp.com',
    storageBucket: 'step-counter-d044d.appspot.com',
    measurementId: 'G-CNS175VZJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqYGTOTKCu41yQy2ufjR-xhdIKPLHxExQ',
    appId: '1:990092518872:android:23b072f53558b3ea3f7ead',
    messagingSenderId: '990092518872',
    projectId: 'step-counter-d044d',
    storageBucket: 'step-counter-d044d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvKdaZHdq4svpmGPyIpf60TJAZzjJcSfY',
    appId: '1:990092518872:ios:c811a4b71f6d827b3f7ead',
    messagingSenderId: '990092518872',
    projectId: 'step-counter-d044d',
    storageBucket: 'step-counter-d044d.appspot.com',
    iosBundleId: 'com.example.stepCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvKdaZHdq4svpmGPyIpf60TJAZzjJcSfY',
    appId: '1:990092518872:ios:94af353d4e3ecb093f7ead',
    messagingSenderId: '990092518872',
    projectId: 'step-counter-d044d',
    storageBucket: 'step-counter-d044d.appspot.com',
    iosBundleId: 'com.example.stepCounter.RunnerTests',
  );
}
